name: MultiLogin
version: @version@
main: moe.caa.multilogin.bukkit.main.MultiLoginBukkit
author: @contributors@
softdepend:
  - ProtocolLib
api-version: 1.13
folia-supported: true
commands:
  multilogin: { }
