[versions]
kotlin = "2.0.0"
shadow = "8.1.1"
git = "3.1.3"
ideaext = "1.1.8"
asm = "9.5"

[libraries]
asm = {group = "org.ow2.asm", name = "asm", version.ref = "asm"}

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
git = { id = "net.kyori.indra.git", version.ref = "git" }
ideaext = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "ideaext" }
eclipse = {id = "eclipse"}