name: 错误报告
description: 报告一个错误以帮助我们改进MultiLogin
title: "[错误报告] "

body:
  - type: markdown
    attributes:
      value: |
        首先，非常感谢您抽出时间来填写此份错误报告
        ! 请注意，任何遗漏了**重要内容**的bug报告我们将会不予理会 !
        ! 请注意，任何修改了**样式模板**的bug报告我们将会不予理会 !
  - type: textarea
    id: bug-description
    attributes:
      label: |
        BUG描述
      description: |
        请告诉我们你遇到了什么问题
      placeholder: |
        包括你尝试了什么，你期望发生什么，以及实际发生了什么。细节越多越好！
    validations:
      required: true
  - type: input
    id: MultiLogin-version
    attributes:
      label: |
        MultiLogin版本
      description: |
        这将在服务器启动时显示
    validations:
      required: true
  - type: input
    id: system-architecture
    attributes:
      label: |
        系统架构
      description: |
        请填写您所使用的是哪种架构，例如`linux/amd64`, `windows/amd64`
    validations:
      required: true
  - type: input
    id: server-core
    attributes:
      label: |
        服务器核心
      description: |
        请填写您所使用的是哪种服务器核心，例如`vanilla/1.21`, `spigot/1..20.4`，如果能带上版本号+commit id就更好了
    validations:
      required: true
  - type: input
    id: config
    attributes:
      label: |
        配置文件
      description: |
        需要您的配置的文件我们才能弄懂错误大致是因为什么发生的，请注意隐藏私密信息
        为避免影响体验，我们需要您提交到<pastebin.com>或者<pastebin.mozilla.org>以及类似的在线剪切板
        然后将生成的链接粘贴至此
    validations:
      required: true
  - type: input
    id: log
    attributes:
      label: |
        日志
      description: |
        ! 请务必**开启插件 DEBUG 日志** !
        ! 请务必**删除其他与BUG无关的插件/Mod** !
        ! 请务必**在对服务端做最小更改的情况下提交日志** !
        需要日志我们才能帮助您解决问题，请注意隐藏私密信息
        为避免影响体验，我们需要您提交到<pastebin.com>或者<pastebin.mozilla.org>以及类似的在线剪切板
        然后将生成的链接粘贴至此
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: |
        复现步骤
      description: |
        如果这是由于操作所产生的，我们需要复现步骤才能更好的解决您的问题
      value: |
        1.
        2.
        3.
        ...
  - type: checkboxes
    id: area
    attributes:
      label: |
        确认一遍
      options:
        - label: "我已完成且认真地填写完了报告所需要的信息"
        - label: "我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)"
